# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 550)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"C:\Users\zhenxs\PycharmProjects\SoftProjectDemo\Game\image\icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))

        self.scoreLabel = QtWidgets.QLabel(self.centralwidget)
        # self.timer . setPixmap(QtGui.QPixmap(r"C:\Users\zhenxs\PycharmProjects\SoftProjectDemo\Game\image\bot.png"))
        self.scoreLabel . setGeometry(QtCore.QRect(70 + 130, 470 , 120, 40))
        self.scoreLabel . setText("0")
        self.scoreLabel . setStyleSheet("background-color: rgb(255,255,255); text-align: center ; font:16pt,'Arial';")
        self.scoreLabel.setAlignment(Qt.AlignCenter)
        # font = QtGui.QFont()
        # font.setsi
        # self.timer.setFont(font)
        self.scoreLabel.setObjectName("Clock")


        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bubble Bomb"))
